apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: rodrigogrohl/questcode-backend-user:0.1.4
        ports:
        - containerPort: 3020
        env:
        - name: NODE_ENV
          value: "staging"
        - name: MONGO_URI
          value: "mongodb://dbuser:dbuser18@192.168.1.12:31133/base-dev"
        - name: SECRET_OR_KEY
          value: "b00tc4mp18"